Login page and different dependencies + local setup of font awesome
JuanFelipeJaramillo20/DS2-frontend pull request #3
Opened 2023-11-30 17:44 UTC by JuanFelipeJaramillo20

Los miles de archivos cambiados bajo la carpeta assets es solo la importacion de fontawesome 5 de manera local, se puede ignorar :)

2023-12-02 23:47 UTC, heisjuanda commented
En el Login podemos eliminar el navigate que no se reemplaza por el componente Link

2023-12-02 23:48 UTC, heisjuanda commented
en el `Login` tambien cambiar la ruta de la url, a una válida, ya sea la que existe actualmente o la nueva que se añadió para reemplazarla en `Routes`

2023-12-02 23:49 UTC, heisjuanda commented
No sé que es `Toast`, solo sé que estamos adictos al gym, y melo eso, pero ese "Gym App" va?
![image](https://github.com/JuanFelipeJaramillo20/DS2-frontend/assets/63882053/084731a6-96f8-4b47-a899-de1aa8fa9c04)

2023-12-02 23:50 UTC, heisjuanda commented
En general mela la pull

2023-12-02 23:54 UTC, heisjuanda requested changes
revise los comentarios de arriba y me dice si sisas o nonas

2023-12-03 03:19 UTC, JuanFelipeJaramillo20 commented
> En el `Login` el `navigate` es para cuando inicie sesión sea llevado a `Dashboard` en el futuro? o solo es para reemplzar el Link`

Si, cuando se implemente el servicio de login la idea es que al iniciar sesion el navigate redirija a dashboad o la pestaña que sigua

2023-12-03 03:22 UTC, JuanFelipeJaramillo20 commented
> No sé que es `Toast`, solo sé que estamos adictos al gym, y melo eso, pero ese "Gym App" va? ![image](https://private-user-images.githubusercontent.com/63882053/287488712-084731a6-96f8-4b47-a899-de1aa8fa9c04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjY4MzQsIm5iZiI6MTcwMTU2NjUzNCwicGF0aCI6Ii82Mzg4MjA1My8yODc0ODg3MTItMDg0NzMxYTYtOTZmOC00YjQ3LWE4OTktZGUxYWE4ZmE5YzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDAxMjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OTM2ODk4OTdkOGI3MzgyZTIyOTc4MzEwZmVmNThjMTczZTRiZWZmNDY1OTRmNjJkYTEzYTVjMWQyNjk4YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TqEQ_0H3PEB_sbn9jYXwwSyKUbD85lmFxT_XhYZVTqY)

Corregido, era copiado de un proyecto viejo

2023-12-03 03:28 UTC, JuanFelipeJaramillo20 commented
Fixes implementados, no entendí lo de la ruta, cualquier cosa extra quedo pendiente para corregir de una vez. 

@heisjuanda

2023-12-03 17:58 UTC, heisjuanda commented
Lo de la ruta es cuando se le da click al "Register" cuando no se tiene cuenta, que lleva al ususario a una ruta que no exite, podemos cambiar la url del component `Link` para que lleve a la ruta existente de registro o cambiar la ruta eixstente por la que se usa en el componente de `Login`
@JuanFelipeJaramillo20

2023-12-03 20:58 UTC, JuanFelipeJaramillo20 commented
> Lo de la ruta es cuando se le da click al "Register" cuando no se tiene cuenta, que lleva al ususario a una ruta que no exite, podemos cambiar la url del component `Link` para que lleve a la ruta existente de registro o cambiar la ruta eixstente por la que se usa en el componente de `Login` @JuanFelipeJaramillo20

Ahh si, corregido.

2023-12-03 21:00 UTC, JuanFelipeJaramillo20 commented
@heisjuanda no se como darle a solicitar review otra vez, :(

2023-12-03 21:08 UTC, heisjuanda approved these changes
Linda la pull, haga los honores del merge @JuanFelipeJaramillo20

2023-12-03 21:12 UTC, merged